default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV["DB_POOL"] || 5  %>
  database: <%= ENV['DB_NAME'] || 'demo_dev' %>
  username: <%= ENV['DB_USER'] || 'root' %>
  password: <%= ENV['DB_PASS'] %>
  host: <%= ENV["DB_HOST"] %>
  url: <%= ENV['DATABASE_URL'] %> # takes higher precedence than other settings

development:
  <<: *default
  database: <%= ENV['DB_NAME'] || 'demo_dev' %>

test:
  <<: *default
  database: livedemo_test

staging:
  <<: *default
  database: livedemo_stag
  url: <%= ENV['DATABASE_URL'] %>

production:
  <<: *default
  database: livedemo_prod
  url: <%= ENV['DATABASE_URL'] %>
